import {
  EventCategory,
  Country,
  City,
  Organization,
  EventItem,
  UserProfile,
  EventReport,
  AuditLog,
  NotificationItem,
  EventPendingChange,
} from '@/types/database';

export const INITIAL_COUNTRIES: Country[] = [
  { id: 'c-de', code: 'DE', name_en: 'Germany', name_ar: 'ألمانيا', name_de: 'Deutschland', name_fr: 'Allemagne' },
  { id: 'c-iq', code: 'IQ', name_en: 'Iraq', name_ar: 'العراق', name_de: 'Irak', name_fr: 'Irak' },
  { id: 'c-fr', code: 'FR', name_en: 'France', name_ar: 'فرنسا', name_de: 'Frankreich', name_fr: 'France' },
  { id: 'c-us', code: 'US', name_en: 'United States', name_ar: 'الولايات المتحدة', name_de: 'Vereinigte Staaten', name_fr: 'États-Unis' },
  { id: 'c-au', code: 'AU', name_en: 'Australia', name_ar: 'أستراليا', name_de: 'Australien', name_fr: 'Australie' },
];

export const INITIAL_CITIES: City[] = [
  { id: 'city-berlin', country_id: 'c-de', name_en: 'Berlin', name_ar: 'برلين', name_de: 'Berlin', name_fr: 'Berlin', latitude: 52.5200, longitude: 13.4050 },
  { id: 'city-hanover', country_id: 'c-de', name_en: 'Hanover', name_ar: 'هانوفر', name_de: 'Hannover', name_fr: 'Hanovre', latitude: 52.3759, longitude: 9.7320 },
  { id: 'city-erbil', country_id: 'c-iq', name_en: 'Erbil', name_ar: 'أربيل', name_de: 'Erbil', name_fr: 'Erbil', latitude: 36.1912, longitude: 44.0091 },
  { id: 'city-lalish', country_id: 'c-iq', name_en: 'Shekhan / Lalish', name_ar: 'شيخان / لالش', name_de: 'Schechan / Lalisch', name_fr: 'Shekhan / Lalish', latitude: 36.7725, longitude: 43.3039 },
  { id: 'city-paris', country_id: 'c-fr', name_en: 'Paris', name_ar: 'باريس', name_de: 'Paris', name_fr: 'Paris', latitude: 48.8566, longitude: 2.3522 },
  { id: 'city-lincoln', country_id: 'c-us', name_en: 'Lincoln (Nebraska)', name_ar: 'لينكولن (نبراسكا)', name_de: 'Lincoln (Nebraska)', name_fr: 'Lincoln (Nebraska)', latitude: 40.8136, longitude: -96.7026 },
  { id: 'city-sydney', country_id: 'c-au', name_en: 'Sydney', name_ar: 'سيدني', name_de: 'Sydney', name_fr: 'Sydney', latitude: -33.8688, longitude: 151.2093 },
];

export const INITIAL_CATEGORIES: EventCategory[] = [
  { id: 'cat-demo', slug: 'demonstration', name_en: 'Demonstration', name_ar: 'مظاهرة', name_de: 'Demonstration', name_fr: 'Manifestation', description: 'Public demonstrations and awareness rallies', icon_name: 'Megaphone' },
  { id: 'cat-solidarity', slug: 'solidarity-rally', name_en: 'Solidarity Rally', name_ar: 'وقفة تضامنية', name_de: 'Solidaritätskundgebung', name_fr: 'Rassemblement de solidarité', description: 'Community and international solidarity rallies', icon_name: 'HeartHandshake' },
  { id: 'cat-vigil', slug: 'vigil', name_en: 'Vigil & Candlelight', name_ar: 'وقفة شموع وتأبين', name_de: 'Mahnwache', name_fr: 'Veillée aux chandelles', description: 'Peaceful vigils and commemorative moments of silence', icon_name: 'Flame' },
  { id: 'cat-memorial', slug: 'memorial', name_en: 'Memorial Event', name_ar: 'ذكرى سنوية وتأبين', name_de: 'Gedenkveranstaltung', name_fr: 'Événement commémoratif', description: 'Annual August 3 Yazidi Genocide memorials', icon_name: 'Monument' },
  { id: 'cat-conference', slug: 'conference', name_en: 'Conference & Panel', name_ar: 'مؤتمر وندوة حوارية', name_de: 'Konferenz & Podium', name_fr: 'Conférence & Débat', description: 'Academic and human rights panels', icon_name: 'Presentation' },
  { id: 'cat-cultural', slug: 'cultural', name_en: 'Cultural Gathering', name_ar: 'فعالية ثقافية وفنية', name_de: 'Kulturveranstaltung', name_fr: 'Événement culturel', description: 'Traditional music, art exhibits and festivals', icon_name: 'Palette' },
  { id: 'cat-rights', slug: 'human-rights', name_en: 'Human Rights Forum', name_ar: 'منتدى حقوق الإنسان', name_de: 'Menschenrechtsforum', name_fr: 'Forum des droits humains', description: 'Advocacy, legal accountability and peace forums', icon_name: 'Scale' },
  { id: 'cat-community', slug: 'community', name_en: 'Community Gathering', name_ar: 'لقاء مجتمعي', name_de: 'Gemeinschaftstreffen', name_fr: 'Rassemblement communautaire', description: 'Diaspora youth and community networking', icon_name: 'Users' },
];

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'user-super-admin',
    email: 'admin@ezidievents.org',
    full_name: 'Platform Super Admin',
    role: 'super_admin',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'user-org-berlin',
    email: 'berlin@demo-yazidi.org',
    full_name: 'Yazidi Global Solidarity Admin',
    role: 'organization_admin',
    created_at: '2026-01-10T00:00:00Z',
    updated_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'user-org-hanover',
    email: 'hanover@demo-lalish.de',
    full_name: 'Lalish Hanover Admin',
    role: 'organization_editor',
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'user-normal',
    email: 'activist@community.org',
    full_name: 'Civic Activist',
    role: 'user',
    created_at: '2026-02-01T00:00:00Z',
    updated_at: '2026-02-01T00:00:00Z',
  },
];

export const INITIAL_ORGANIZATIONS: Organization[] = [
  {
    id: 'org-1',
    name: '[Demo] Yazidi Global Solidarity Initiative',
    slug: 'demo-yazidi-global-solidarity',
    password: 'Ezidi@2026',
    logo: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=200&h=200&fit=crop',
    cover_image: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=1200&h=400&fit=crop',
    description: 'An international non-governmental alliance dedicated to human rights, justice, and documenting Yazidi community events worldwide.',
    name_ar: '[تجريبي] المبادرة العالمية للتضامن الإيزيدي',
    description_ar: 'تحالف دولي غير حكومي مكرس لحقوق الإنسان والعدالة وتوثيق الفعاليات الإيزيدية حول العالم.',
    organization_type: 'Human Rights NGO',
    country_id: 'c-de',
    city_id: 'city-berlin',
    full_address: 'Pariser Platz 1, 10117 Berlin, Germany',
    latitude: 52.5163,
    longitude: 13.3777,
    website: 'https://example.org/yazidi-global',
    email: 'contact@demo-yazidi-solidarity.org',
    phone: '+49 30 1234567',
    organization_status: 'active',
    verification_status: 'verified',
    verified_at: '2026-01-15T10:00:00Z',
    verified_by: 'user-super-admin',
    verification_notes: 'Verified via official German registry documentation.',
    direct_publishing_enabled: true,
    is_demo: true,
    created_at: '2026-01-10T00:00:00Z',
    updated_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'org-2',
    name: '[Demo] Lalish Cultural & Heritage Center',
    slug: 'demo-lalish-cultural-center',
    password: 'Ezidi@2026',
    logo: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=200&h=200&fit=crop',
    cover_image: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&h=400&fit=crop',
    description: 'Preserving Ezidi cultural heritage, oral traditions, sacred architecture, and youth educational workshops across Europe.',
    name_ar: '[تجريبي] مركز لالش للثقافة والتراث الإيزيدي',
    description_ar: 'الحفاظ على التراث الثقافي الإيزيدي والتقاليد الشفهية والفعاليات المجتمعية في أوروبا.',
    organization_type: 'Cultural Association',
    country_id: 'c-de',
    city_id: 'city-hanover',
    full_address: 'Kröpcke 5, 30159 Hannover, Germany',
    latitude: 52.3745,
    longitude: 9.7386,
    website: 'https://example.org/lalish-center',
    email: 'info@demo-lalish-center.de',
    phone: '+49 511 7654321',
    organization_status: 'active',
    verification_status: 'verified',
    verified_at: '2026-02-01T12:00:00Z',
    verified_by: 'user-super-admin',
    verification_notes: 'Registered cultural non-profit in Lower Saxony.',
    direct_publishing_enabled: false, // Verified but submissions go through admin review
    is_demo: true,
    created_at: '2026-01-20T00:00:00Z',
    updated_at: '2026-02-01T00:00:00Z',
  },
  {
    id: 'org-3',
    name: '[Demo] Youth for Yazidi Peace & Justice',
    slug: 'demo-youth-yazidi-peace',
    password: 'Ezidi@2026',
    logo: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=200&h=200&fit=crop',
    cover_image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1200&h=400&fit=crop',
    description: 'A student and youth-led movement advocating for educational grants, youth cultural exchanges, and human rights.',
    name_ar: '[تجريبي] شباب من أجل السلام والعدالة الإيزيدية',
    description_ar: 'حركة شبابية وطلابية تدعو للسلام ودعم الشباب الإيزيدي في المهجر والوطن.',
    organization_type: 'Youth Association',
    country_id: 'c-fr',
    city_id: 'city-paris',
    full_address: 'Place de la République, 75011 Paris, France',
    latitude: 48.8675,
    longitude: 2.3638,
    website: 'https://example.org/youth-yazidi',
    email: 'contact@demo-youth-yazidi.fr',
    organization_status: 'active',
    verification_status: 'pending',
    direct_publishing_enabled: false,
    is_demo: true,
    created_at: '2026-03-01T00:00:00Z',
    updated_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'org-4',
    name: '[Demo] Suspended Example Organization',
    slug: 'demo-suspended-example-org',
    password: 'Ezidi@2026',
    logo: 'https://images.unsplash.com/photo-1572945116067-7f549c7556f8?w=200&h=200&fit=crop',
    cover_image: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=1200&h=400&fit=crop',
    description: 'Demonstration organization demonstrating suspended status and automatic revocation of publishing permissions.',
    organization_type: 'Community Association',
    country_id: 'c-de',
    city_id: 'city-berlin',
    full_address: 'Alexanderplatz 1, 10178 Berlin, Germany',
    latitude: 52.5219,
    longitude: 13.4132,
    email: 'info@demo-suspended.org',
    organization_status: 'suspended',
    verification_status: 'suspended',
    direct_publishing_enabled: false,
    is_demo: true,
    created_at: '2026-02-10T00:00:00Z',
    updated_at: '2026-03-15T00:00:00Z',
  },
];

export const INITIAL_EVENTS: EventItem[] = [
  {
    id: 'event-1',
    slug: 'berlin-international-solidarity-rally-2026',
    title: 'International Solidarity Rally for Yazidi Justice & Genocide Recognition',
    title_ar: 'وقفة تضامنية دولية لتحقيق العدالة للإيزيديين والاعتراف بالإبادة الجماعية',
    title_de: 'Internationale Solidaritätskundgebung für Jesidische Gerechtigkeit',
    title_fr: 'Rassemblement international de solidarité pour la justice yézidie',
    description: 'Join civil society organizations, human rights advocates, and community members in front of the historic Brandenburg Gate for speeches, moments of silence, and calls for international accountability.',
    description_ar: 'انضم إلى منظمات المجتمع المدني والمدافعين عن حقوق الإنسان أمام بوابة براندنبورغ التاريخية للمطالبة بالعدالة الدولية.',
    description_de: 'Schließen Sie sich zivilgesellschaftlichen Organisationen vor dem Brandenburger Tor an.',
    description_fr: 'Rejoignez les organisations des droits humains devant la porte de Brandebourg.',
    category_id: 'cat-solidarity',
    date: '2026-08-03',
    start_time: '16:00',
    end_time: '19:30',
    timezone: 'Europe/Berlin',
    country_id: 'c-de',
    city_id: 'city-berlin',
    full_address: 'Pariser Platz, 10117 Berlin, Germany',
    postal_code: '10117',
    street: 'Pariser Platz',
    house_number: '1',
    latitude: 52.5163,
    longitude: 13.3777,
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=52.5163,13.3777',
    organization_id: 'org-1',
    organizer_name: '[Demo] Yazidi Global Solidarity Initiative',
    poster_url: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=800&h=1000&fit=crop',
    status: 'published',
    visibility: 'public',
    event_verification_status: 'organization_verified',
    is_featured: true,
    is_demo: true,
    source_url: 'https://example.org/yazidi-global/berlin-rally-2026',
    sources: [
      {
        id: 'src-1',
        event_id: 'event-1',
        source_type: 'official_organization',
        source_url: 'https://example.org/yazidi-global/berlin-rally-2026',
        source_title: 'Official Press Release: Berlin Rally 2026',
        source_organization: '[Demo] Yazidi Global Solidarity Initiative',
        source_date: '2026-06-01',
        is_public: true,
        created_at: '2026-06-01T00:00:00Z',
        updated_at: '2026-06-01T00:00:00Z',
      },
    ],
    contact_email: 'events@demo-yazidi-solidarity.org',
    created_at: '2026-06-01T00:00:00Z',
    updated_at: '2026-06-01T00:00:00Z',
  },
  {
    id: 'event-2',
    slug: 'lalish-annual-heritage-peace-conference-2026',
    title: 'Lalish Peace & Cultural Heritage Forum 2026',
    title_ar: 'منتدى لالش للسلام والتراث الثقافي 2026',
    title_de: 'Lalisch Friedens- und Kulturerbeforum 2026',
    title_fr: 'Forum de la paix et du patrimoine de Lalish 2026',
    description: 'An international conference gathering community elders, youth delegates, and cultural historians discussing preservation of ancient sacred traditions and rebuilding heritage in Sinjar and Shekhan.',
    category_id: 'cat-conference',
    date: '2026-08-15',
    start_time: '10:00',
    end_time: '18:00',
    timezone: 'Asia/Baghdad',
    country_id: 'c-iq',
    city_id: 'city-lalish',
    full_address: 'Lalish Temple Complex, Shekhan District, Nineveh Plains, Iraq',
    latitude: 36.7725,
    longitude: 43.3039,
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=36.7725,43.3039',
    organization_id: 'org-2',
    organizer_name: '[Demo] Lalish Cultural Center & Elders Council',
    poster_url: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&h=1000&fit=crop',
    status: 'published',
    visibility: 'public',
    event_verification_status: 'admin_verified',
    is_featured: true,
    is_demo: true,
    source_url: 'https://example.org/lalish-conference-2026',
    contact_email: 'info@demo-lalish-center.de',
    created_at: '2026-06-10T00:00:00Z',
    updated_at: '2026-06-15T00:00:00Z',
  },
  {
    id: 'event-3',
    slug: 'paris-candlelight-vigil-for-sinjar-survivors',
    title: 'Paris Vigil of Light: In Memory of Sinjar Victims',
    title_ar: 'وقفة شموع في باريس: وفاءً لضحايا وناجيات سنجار',
    title_de: 'Pariser Lichter-Mahnwache für die Überlebenden von Sindschar',
    title_fr: 'Veillée aux bougies à Paris : En mémoire des victimes de Sinjar',
    description: 'Candlelight vigil, acoustic traditional melodies, and reading of survivor testimonies at Place de la République in central Paris.',
    category_id: 'cat-vigil',
    date: '2026-08-03',
    start_time: '19:30',
    end_time: '22:00',
    timezone: 'Europe/Paris',
    country_id: 'c-fr',
    city_id: 'city-paris',
    full_address: 'Place de la République, 75011 Paris, France',
    latitude: 48.8675,
    longitude: 2.3638,
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=48.8675,2.3638',
    organizer_name: 'French-Yazidi Community Solidarity Network',
    poster_url: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&h=1000&fit=crop',
    status: 'published',
    visibility: 'public',
    event_verification_status: 'admin_verified',
    is_featured: false,
    is_demo: true,
    source_url: 'https://example.org/paris-vigil-2026',
    contact_email: 'contact@demo-youth-yazidi.fr',
    created_at: '2026-06-20T00:00:00Z',
    updated_at: '2026-06-20T00:00:00Z',
  },
  {
    id: 'event-4',
    slug: 'lincoln-nebraska-yazidi-culture-and-food-fair',
    title: 'North American Yazidi Heritage & Cultural Exhibition',
    title_ar: 'معرض التراث والثقافة الإيزيدية في أمريكا الشمالية',
    title_de: 'Nordamerikanische Jesidische Kultur- und Kunstausstellung',
    title_fr: 'Exposition du patrimoine et de la culture yézidie d’Amérique du Nord',
    description: 'Featuring traditional Yazidi handicrafts, bread-making demonstrations, photo exhibits of Sinjar before and after 2014, and cultural music.',
    category_id: 'cat-cultural',
    date: '2026-09-12',
    start_time: '11:00',
    end_time: '17:00',
    timezone: 'America/Chicago',
    country_id: 'c-us',
    city_id: 'city-lincoln',
    full_address: '1500 R St, Lincoln, NE 68588, United States',
    latitude: 40.8176,
    longitude: -96.7005,
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=40.8176,-96.7005',
    organizer_name: 'Yazidi Community Association of Nebraska',
    poster_url: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800&h=1000&fit=crop',
    status: 'published',
    visibility: 'public',
    event_verification_status: 'admin_verified',
    is_featured: false,
    is_demo: true,
    source_url: 'https://example.org/nebraska-yazidi-fair',
    created_at: '2026-06-22T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
  {
    id: 'event-5',
    slug: 'sydney-human-rights-memorial-march',
    title: 'Sydney Solidarity March for Global Genocide Prevention & Justice',
    title_ar: 'مسيرة تضامنية في سيدني للعدالة ومنع الإبادة الجماعية',
    title_de: 'Sydney Solidaritätsmarsch zur Verhinderung von Völkermord',
    title_fr: 'Marche de solidarité à Sydney pour la prévention des génocides',
    description: 'A peaceful march from Hyde Park to Martin Place calling on parliamentarians to support post-genocide rehabilitation and mental health support programs.',
    category_id: 'cat-rights',
    date: '2026-08-08',
    start_time: '14:00',
    end_time: '17:00',
    timezone: 'Australia/Sydney',
    country_id: 'c-au',
    city_id: 'city-sydney',
    full_address: 'Elizabeth St, Hyde Park, Sydney NSW 2000, Australia',
    latitude: -33.8732,
    longitude: 151.2106,
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=-33.8732,151.2106',
    organizer_name: 'Australian Yazidi Community Council',
    poster_url: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&h=1000&fit=crop',
    status: 'published',
    visibility: 'public',
    event_verification_status: 'unverified',
    is_featured: false,
    is_demo: true,
    source_url: 'https://example.org/sydney-march',
    created_at: '2026-06-25T00:00:00Z',
    updated_at: '2026-06-25T00:00:00Z',
  },
  // Pending Submission (For Admin Submissions Review testing)
  {
    id: 'event-pending-1',
    slug: 'hanover-youth-symposium-2026',
    title: 'Hanover Yazidi Diaspora Youth Symposium 2026',
    title_ar: 'ندوة شباب المهجر الإيزيدي في هانوفر 2026',
    title_de: 'Hannover Jesidisches Diaspora-Jugendsymposium 2026',
    title_fr: 'Symposium de la jeunesse yézidie à Hanovre 2026',
    description: 'Workshops on mother tongue education, integration challenges, cultural identity, and youth empowerment.',
    category_id: 'cat-community',
    date: '2026-09-26',
    start_time: '13:00',
    end_time: '18:00',
    timezone: 'Europe/Berlin',
    country_id: 'c-de',
    city_id: 'city-hanover',
    full_address: 'Kröpcke 5, 30159 Hannover, Germany',
    latitude: 52.3745,
    longitude: 9.7386,
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=52.3745,9.7386',
    organizer_name: 'Hanover Yazidi Student Union',
    poster_url: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&h=1000&fit=crop',
    status: 'pending',
    visibility: 'private',
    event_verification_status: 'unverified',
    is_demo: true,
    source_url: 'https://example.org/hanover-youth',
    contact_email: 'youth@demo-hanover.de',
    created_at: '2026-07-01T00:00:00Z',
    updated_at: '2026-07-01T00:00:00Z',
  },
  // Cancelled Event (For status testing)
  {
    id: 'event-cancelled-1',
    slug: 'frankfurt-peace-dialogue-cancelled',
    title: 'Frankfurt Interfaith Dialogue Forum (Postponed / Rescheduling)',
    title_ar: 'منتدى فرانكفورت للحوار (تم التأجيل لإعادة الجدولة)',
    title_de: 'Frankfurter Friedensdialogforum (Verschoben)',
    title_fr: 'Forum de dialogue de Francfort (Reporté)',
    description: 'This dialogue event is currently postponed and will be rescheduled for autumn 2026.',
    category_id: 'cat-conference',
    date: '2026-07-10',
    start_time: '15:00',
    end_time: '18:00',
    timezone: 'Europe/Berlin',
    country_id: 'c-de',
    city_id: 'city-berlin',
    full_address: 'Frankfurt am Main, Germany',
    latitude: 50.1109,
    longitude: 8.6821,
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=50.1109,8.6821',
    organizer_name: 'Interfaith Justice Coalition',
    status: 'cancelled',
    visibility: 'public',
    event_verification_status: 'admin_verified',
    is_demo: true,
    created_at: '2026-05-01T00:00:00Z',
    updated_at: '2026-06-28T00:00:00Z',
  },
];

export const INITIAL_PENDING_CHANGES: EventPendingChange[] = [
  {
    id: 'change-1',
    event_id: 'event-1',
    proposed_data: {
      date: '2026-08-04',
      start_time: '17:00',
      end_time: '20:30',
      full_address: 'Unter den Linden 77, 10117 Berlin, Germany',
      latitude: 52.5160,
      longitude: 13.3800,
    },
    changed_fields: ['date', 'start_time', 'end_time', 'full_address', 'latitude', 'longitude'],
    submitted_by: 'user-org-berlin',
    status: 'pending',
    admin_notes: null,
    created_at: '2026-07-02T14:30:00Z',
  },
];

export const INITIAL_REPORTS: EventReport[] = [
  {
    id: 'report-1',
    event_id: 'event-5',
    reporter_name: 'Community Observer',
    reporter_email: 'observer@sydney.au',
    report_type: 'wrong_location',
    description: 'The starting point has moved from central lawn to the north entrance near St James Station.',
    status: 'open',
    created_at: '2026-07-03T09:15:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-seed-1',
    actor_id: 'user-super-admin',
    actor_email: 'admin@ezidievents.org',
    actor_role: 'super_admin',
    action: 'ORGANIZATION_VERIFIED',
    entity_type: 'organization',
    entity_id: 'org-1',
    reason: 'Verified official documentation and NGO non-profit charter.',
    previous_values: { verification_status: 'pending' },
    new_values: { verification_status: 'verified' },
    created_at: '2026-01-15T10:00:00Z',
  },
  {
    id: 'audit-seed-2',
    actor_id: 'user-super-admin',
    actor_email: 'admin@ezidievents.org',
    actor_role: 'super_admin',
    action: 'DIRECT_PUBLISHING_ENABLED',
    entity_type: 'organization',
    entity_id: 'org-1',
    reason: 'Trusted international organization with verified publication accuracy record.',
    previous_values: { direct_publishing_enabled: false },
    new_values: { direct_publishing_enabled: true },
    created_at: '2026-01-15T10:05:00Z',
  },
  {
    id: 'audit-seed-3',
    actor_id: 'user-super-admin',
    actor_email: 'admin@ezidievents.org',
    actor_role: 'super_admin',
    action: 'ORGANIZATION_SUSPENDED',
    entity_type: 'organization',
    entity_id: 'org-4',
    reason: 'Repeated inaccurate location submissions and spam complaints.',
    previous_values: { organization_status: 'active', direct_publishing_enabled: false },
    new_values: { organization_status: 'suspended', direct_publishing_enabled: false },
    created_at: '2026-03-15T11:20:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    user_id: 'user-super-admin',
    title: 'New Event Submission Awaiting Moderation',
    message: 'Hanover Yazidi Diaspora Youth Symposium 2026 was submitted for review.',
    type: 'warning',
    link: '/admin/submissions',
    is_read: false,
    created_at: '2026-07-01T00:00:00Z',
  },
  {
    id: 'notif-2',
    user_id: 'user-super-admin',
    title: 'Pending Sensitive Change Request',
    message: 'Yazidi Global Solidarity Initiative requested a date & venue update for Berlin Solidarity Rally.',
    type: 'info',
    link: '/admin/pending-changes',
    is_read: false,
    created_at: '2026-07-02T14:30:00Z',
  },
];
