import {
  EventItem,
  Organization,
  EventCategory,
  Country,
  City,
  EventReport,
  AuditLog,
  NotificationItem,
  UserProfile,
  EventPendingChange,
} from '@/types/database';

export const INITIAL_COUNTRIES: Country[] = [
  { id: 'c-iq', code: 'IQ', name_en: 'Iraq', name_ar: 'العراق', name_de: 'Irak', name_fr: 'Irak' },
  { id: 'c-de', code: 'DE', name_en: 'Germany', name_ar: 'ألمانيا', name_de: 'Deutschland', name_fr: 'Allemagne' },
  { id: 'c-fr', code: 'FR', name_en: 'France', name_ar: 'فرنسا', name_de: 'Frankreich', name_fr: 'France' },
  { id: 'c-se', code: 'SE', name_en: 'Sweden', name_ar: 'السويد', name_de: 'Schweden', name_fr: 'Suède' },
  { id: 'c-nl', code: 'NL', name_en: 'Netherlands', name_ar: 'هولندا', name_de: 'Niederlande', name_fr: 'Pays-Bas' },
  { id: 'c-us', code: 'US', name_en: 'United States', name_ar: 'الولايات المتحدة', name_de: 'Vereinigte Staaten', name_fr: 'États-Unis' },
  { id: 'c-ca', code: 'CA', name_en: 'Canada', name_ar: 'كندا', name_de: 'Kanada', name_fr: 'Canada' },
  { id: 'c-au', code: 'AU', name_en: 'Australia', name_ar: 'أستراليا', name_de: 'Australien', name_fr: 'Australie' },
  { id: 'c-am', code: 'AM', name_en: 'Armenia', name_ar: 'أرمينيا', name_de: 'Armenien', name_fr: 'Arménie' },
  { id: 'c-ge', code: 'GE', name_en: 'Georgia', name_ar: 'جورجيا', name_de: 'Georgien', name_fr: 'Géorgie' },
];

export const INITIAL_CITIES: City[] = [
  { id: 'city-berlin', country_id: 'c-de', name_en: 'Berlin', name_ar: 'برلين', name_de: 'Berlin', name_fr: 'Berlin', latitude: 52.5200, longitude: 13.4050 },
  { id: 'city-hanover', country_id: 'c-de', name_en: 'Hannover', name_ar: 'هانوفر', name_de: 'Hannover', name_fr: 'Hanovre', latitude: 52.3759, longitude: 9.7320 },
  { id: 'city-celle', country_id: 'c-de', name_en: 'Celle', name_ar: 'تسيله', name_de: 'Celle', name_fr: 'Celle', latitude: 52.6248, longitude: 10.0807 },
  { id: 'city-bielefeld', country_id: 'c-de', name_en: 'Bielefeld', name_ar: 'بيليفيلد', name_de: 'Bielefeld', name_fr: 'Bielefeld', latitude: 52.0302, longitude: 8.5325 },
  { id: 'city-oldenburg', country_id: 'c-de', name_en: 'Oldenburg', name_ar: 'أولدنبورغ', name_de: 'Oldenburg', name_fr: 'Oldenbourg', latitude: 53.1435, longitude: 8.2146 },
  { id: 'city-cologne', country_id: 'c-de', name_en: 'Cologne', name_ar: 'كولونيا', name_de: 'Köln', name_fr: 'Cologne', latitude: 50.9375, longitude: 6.9603 },
  { id: 'city-sinjar', country_id: 'c-iq', name_en: 'Sinjar (Shingal)', name_ar: 'سنجار (شنكال)', name_de: 'Sindschar', name_fr: 'Sinjar', latitude: 36.3209, longitude: 41.8754 },
  { id: 'city-duhok', country_id: 'c-iq', name_en: 'Duhok', name_ar: 'دهوك', name_de: 'Dohuk', name_fr: 'Dahuk', latitude: 36.8679, longitude: 42.9886 },
  { id: 'city-erbil', country_id: 'c-iq', name_en: 'Erbil', name_ar: 'أربيل', name_de: 'Erbil', name_fr: 'Erbil', latitude: 36.1912, longitude: 44.0091 },
  { id: 'city-lalish', country_id: 'c-iq', name_en: 'Shekhan / Lalish', name_ar: 'شيخان / لالش', name_de: 'Schechan / Lalisch', name_fr: 'Shekhan / Lalish', latitude: 36.7725, longitude: 43.3039 },
  { id: 'city-paris', country_id: 'c-fr', name_en: 'Paris', name_ar: 'باريس', name_de: 'Paris', name_fr: 'Paris', latitude: 48.8566, longitude: 2.3522 },
  { id: 'city-lincoln', country_id: 'c-us', name_en: 'Lincoln (Nebraska)', name_ar: 'لينكولن (نبراسكا)', name_de: 'Lincoln (Nebraska)', name_fr: 'Lincoln (Nebraska)', latitude: 40.8136, longitude: -96.7026 },
  { id: 'city-sydney', country_id: 'c-au', name_en: 'Sydney', name_ar: 'سيدني', name_de: 'Sydney', name_fr: 'Sydney', latitude: -33.8688, longitude: 151.2093 },
];

export const INITIAL_CATEGORIES: EventCategory[] = [
  { id: 'cat-protest', slug: 'demonstration', name_en: 'Demonstration & Rally', name_ar: 'مظاهرة ووقفة تضامنية', name_de: 'Demonstration', name_fr: 'Manifestation', description: 'Public demonstrations and international solidarity rallies', icon_name: 'Megaphone' },
  { id: 'cat-solidarity', slug: 'solidarity-rally', name_en: 'Solidarity Rally', name_ar: 'وقفة تضامنية', name_de: 'Solidaritätskundgebung', name_fr: 'Rassemblement de solidarité', description: 'Community and international solidarity rallies', icon_name: 'HeartHandshake' },
  { id: 'cat-vigil', slug: 'vigil', name_en: 'Vigil & Candlelight', name_ar: 'وقفة شموع وتأبين', name_de: 'Mahnwache', name_fr: 'Veillée aux chandelles', description: 'Peaceful vigils and commemorative moments of silence', icon_name: 'Flame' },
  { id: 'cat-memorial', slug: 'memorial', name_en: 'Genocide Memorial', name_ar: 'ذكرى الإبادة والتأبين', name_de: 'Gedenkveranstaltung', name_fr: 'Événement commémoratif', description: 'Annual August 3 Yazidi Genocide memorials and remembrance', icon_name: 'Monument' },
  { id: 'cat-conf', slug: 'conference', name_en: 'Conference & Panel', name_ar: 'مؤتمر وندوة حوارية', name_de: 'Konferenz & Podium', name_fr: 'Conférence & Débat', description: 'Academic, legal accountability and human rights panels', icon_name: 'Presentation' },
  { id: 'cat-culture', slug: 'cultural', name_en: 'Cultural Gathering & Festival', name_ar: 'فعالية ثقافية وتراثية', name_de: 'Kulturveranstaltung', name_fr: 'Événement culturel', description: 'Traditional Yazidi music, art exhibits and holidays', icon_name: 'Palette' },
  { id: 'cat-rights', slug: 'human-rights', name_en: 'Human Rights Forum', name_ar: 'منتدى حقوق الإنسان', name_de: 'Menschenrechtsforum', name_fr: 'Forum des droits humains', description: 'Advocacy, legal accountability and peace forums', icon_name: 'Scale' },
  { id: 'cat-community', slug: 'community', name_en: 'Community Gathering', name_ar: 'لقاء مجتمعي', name_de: 'Gemeinschaftstreffen', name_fr: 'Rassemblement communautaire', description: 'Diaspora youth and community networking', icon_name: 'Users' },
];

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'user-super-admin',
    email: 'admin@ezidievents.org',
    full_name: 'مدير منصة الفعاليات الإيزيدية',
    role: 'super_admin',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'user-org-ezidi-world',
    email: 'contact@ezidi-world.org',
    full_name: 'Ezidi World Representative',
    role: 'organization_admin',
    created_at: '2026-01-10T00:00:00Z',
    updated_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'user-org-lalish',
    email: 'contact@lalish-center.org',
    full_name: 'Lalish Cultural Representative',
    role: 'organization_admin',
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-01-15T00:00:00Z',
  },
];

export const INITIAL_ORGANIZATIONS: Organization[] = [
  {
    id: 'org-ezidi-world-1786313319017',
    name: 'Ezidi world',
    name_ar: 'عالم الإيزيديين',
    slug: 'org-ezidi-world',
    password: 'Ezidi@2026',
    logo: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=200&h=200&fit=crop',
    cover_image: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=1200&h=400&fit=crop',
    description: 'منظمة توثيق ومتابعة شؤون المجتمع الإيزيدي حول العالم والدفاع عن حقوقه ونشر الفعاليات المجتمعية والدولية.',
    description_ar: 'منظمة توثيق ومتابعة شؤون المجتمع الإيزيدي حول العالم والدفاع عن حقوقه ونشر الفعاليات المجتمعية والدولية.',
    organization_type: 'Human Rights NGO',
    country_id: 'ألمانيا (Germany)',
    city_id: 'برلين (Berlin)',
    full_address: 'Berlin, Germany',
    latitude: 52.5200,
    longitude: 13.4050,
    email: 'contact@ezidi-world.org',
    phone: '+49 30 9876543',
    website: 'https://ezidi-world.org',
    organization_status: 'active',
    verification_status: 'verified',
    verified_at: '2026-08-01T00:00:00Z',
    verified_by: 'user-super-admin',
    direct_publishing_enabled: true,
    is_demo: false,
    created_at: '2026-08-01T00:00:00Z',
    updated_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'org-lalish-center',
    name: 'Lalish Cultural & Heritage Center',
    name_ar: 'مركز لالش الثقافي والاجتماعي',
    slug: 'lalish-cultural-center',
    password: 'Ezidi@2026',
    logo: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=200&h=200&fit=crop',
    cover_image: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&h=400&fit=crop',
    description: 'مركز معني بالحفاظ على التراث الديني والثقافي الإيزيدي وتوثيق المناسبات الدينية في لالش وسنجار والمهجر.',
    description_ar: 'مركز معني بالحفاظ على التراث الديني والثقافي الإيزيدي وتوثيق المناسبات الدينية في لالش وسنجار والمهجر.',
    organization_type: 'Cultural Association',
    country_id: 'ألمانيا (Germany)',
    city_id: 'هانوفر (Hannover)',
    full_address: 'Kröpcke 5, 30159 Hannover, Germany',
    latitude: 52.3745,
    longitude: 9.7386,
    website: 'https://lalish-center.org',
    email: 'contact@lalish-center.org',
    phone: '+49 511 7654321',
    organization_status: 'active',
    verification_status: 'verified',
    verified_at: '2026-02-01T12:00:00Z',
    verified_by: 'user-super-admin',
    direct_publishing_enabled: true,
    is_demo: false,
    created_at: '2026-01-20T00:00:00Z',
    updated_at: '2026-02-01T00:00:00Z',
  },
  {
    id: 'org-yazidi-solidarity',
    name: 'Yazidi Global Solidarity Initiative',
    name_ar: 'المبادرة العالمية للتضامن الإيزيدي',
    slug: 'yazidi-global-solidarity',
    password: 'Ezidi@2026',
    logo: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=200&h=200&fit=crop',
    cover_image: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=1200&h=400&fit=crop',
    description: 'تحالف حقوقي وإنساني دولي يعمل على توثيق جرائم الإبادة والمطالبة بالعدالة ودعم الناجيات في المحافل الدولية.',
    description_ar: 'تحالف حقوقي وإنساني دولي يعمل على توثيق جرائم الإبادة والمطالبة بالعدالة ودعم الناجيات في المحافل الدولية.',
    organization_type: 'Human Rights NGO',
    country_id: 'ألمانيا (Germany)',
    city_id: 'برلين (Berlin)',
    full_address: 'Pariser Platz 1, 10117 Berlin, Germany',
    latitude: 52.5163,
    longitude: 13.3777,
    website: 'https://yazidi-solidarity.org',
    email: 'contact@yazidi-solidarity.org',
    phone: '+49 30 1234567',
    organization_status: 'active',
    verification_status: 'verified',
    verified_at: '2026-01-15T10:00:00Z',
    verified_by: 'user-super-admin',
    direct_publishing_enabled: true,
    is_demo: false,
    created_at: '2026-01-10T00:00:00Z',
    updated_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'org-youth-peace',
    name: 'Youth for Yazidi Peace & Justice',
    name_ar: 'منظمة الشباب الإيزيدي للسلام والعدالة',
    slug: 'youth-yazidi-peace',
    password: 'Ezidi@2026',
    logo: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=200&h=200&fit=crop',
    cover_image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1200&h=400&fit=crop',
    description: 'حركة شبابية وطلابية تعمل على تمكين الأجيال الصاعدة من الإيزيديين في أوروبا وتوثيق الفعاليات الثقافية.',
    description_ar: 'حركة شبابية وطلابية تعمل على تمكين الأجيال الصاعدة من الإيزيديين في أوروبا وتوثيق الفعاليات الثقافية.',
    organization_type: 'Youth Association',
    country_id: 'فرنسا (France)',
    city_id: 'باريس (Paris)',
    full_address: 'Place de la République, 75011 Paris, France',
    latitude: 48.8675,
    longitude: 2.3638,
    website: 'https://youth-yazidi.fr',
    email: 'contact@youth-yazidi.fr',
    organization_status: 'active',
    verification_status: 'verified',
    direct_publishing_enabled: true,
    is_demo: false,
    created_at: '2026-03-01T00:00:00Z',
    updated_at: '2026-03-01T00:00:00Z',
  },
];

export const INITIAL_EVENTS: EventItem[] = [
  {
    id: 'event-ezidi-1',
    slug: '3-ab-memorial-sinjar-rally',
    title: '3 اب - وقفة إحياء ذكرى الإبادة الإيزيدية',
    title_ar: '3 اب - وقفة إحياء ذكرى الإبادة الإيزيدية والمطالبة بالعدالة الدولية',
    title_de: '3. August - Jesidische Völkermord-Gedenkkundgebung',
    title_fr: '3 Août - Rassemblement commémoratif du génocide yézidi',
    description: 'فعالية إحياء ذكرى الإبادة الجماعية للإيزيديين في سنجار وتنظيم وقفة تضامنية واسعة بمشاركة شخصيات حقوقية ودولية.',
    description_ar: 'فعالية إحياء ذكرى الإبادة الجماعية للإيزيديين في سنجار وتنظيم وقفة تضامنية واسعة بمشاركة شخصيات حقوقية ودولية.',
    category_id: 'cat-protest',
    date: '2026-08-27',
    start_time: '16:00',
    end_time: '19:00',
    timezone: 'Europe/Berlin',
    country_id: 'ألمانيا (Germany)',
    city_id: 'برلين (Berlin)',
    full_address: 'Unter den Linden 1, 10178 Berlin, Germany',
    latitude: 52.5163,
    longitude: 13.3777,
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=52.5163,13.3777',
    organization_id: 'org-ezidi-world-1786313319017',
    organizer_name: 'Ezidi world',
    contact_email: 'contact@ezidi-world.org',
    poster_url: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=800&h=1000&fit=crop',
    status: 'published',
    visibility: 'public',
    event_verification_status: 'organization_verified',
    is_featured: true,
    is_demo: false,
    created_at: '2026-08-10T15:00:00Z',
    updated_at: '2026-08-10T15:00:00Z',
  },
  {
    id: 'event-ezidi-2',
    slug: 'abadatona-conference-berlin',
    title: 'ابادتنا: مؤتمر التوثيق والعدالة الدولية',
    title_ar: 'ابادتنا: مؤتمر التوثيق والعدالة الدولية ومحاسبة المتورطين',
    title_de: 'Unser Völkermord: Konferenz für Dokumentation und Gerechtigkeit',
    title_fr: 'Notre génocide : Conférence sur la documentation et la justice',
    description: 'مؤتمر توثيقي شامل حول الإبادة الإيزيدية وسبل تحقيق العدالة للضحايا والناجيات ومتابعة محاكمة المتورطين.',
    description_ar: 'مؤتمر توثيقي شامل حول الإبادة الإيزيدية وسبل تحقيق العدالة للضحايا والناجيات ومتابعة محاكمة المتورطين.',
    category_id: 'cat-conf',
    date: '2026-09-04',
    start_time: '16:00',
    end_time: '19:00',
    timezone: 'Europe/Berlin',
    country_id: 'ألمانيا (Germany)',
    city_id: 'برلين (Berlin)',
    full_address: 'Berlin, Deutschland',
    latitude: 52.5200,
    longitude: 13.4050,
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=52.5200,13.4050',
    organization_id: 'org-ezidi-world-1786313319017',
    organizer_name: 'Ezidi world',
    contact_email: 'contact@ezidi-world.org',
    poster_url: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&h=1000&fit=crop',
    status: 'published',
    visibility: 'public',
    event_verification_status: 'organization_verified',
    is_featured: false,
    is_demo: false,
    created_at: '2026-08-10T15:10:00Z',
    updated_at: '2026-08-10T15:10:00Z',
  },
  {
    id: 'event-ezidi-3',
    slug: 'aaabadatona-exhibition-testimony',
    title: 'ااابادتنا: معرض الصور والشهادات الحية',
    title_ar: 'ااابادتنا: معرض الصور والشهادات الحية للناجين والناجيات',
    title_de: 'Fotoausstellung und Zeugenaussagen zur Sindschar-Tragödie',
    title_fr: 'Exposition photo et témoignages vivants sur Sinjar',
    description: 'معرض توثيقي يضم صوراً حصرية وشهادات حية تروي أحداث الإبادة في شنكال وتضحيات الشعب الإيزيدي وصموده.',
    description_ar: 'معرض توثيقي يضم صوراً حصرية وشهادات حية تروي أحداث الإبادة في شنكال وتضحيات الشعب الإيزيدي وصموده.',
    category_id: 'cat-culture',
    date: '2026-08-27',
    start_time: '16:00',
    end_time: '19:00',
    timezone: 'Europe/Berlin',
    country_id: 'ألمانيا (Germany)',
    city_id: 'برلين (Berlin)',
    full_address: 'Berlin, Deutschland',
    latitude: 52.5200,
    longitude: 13.4050,
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=52.5200,13.4050',
    organization_id: 'org-ezidi-world-1786313319017',
    organizer_name: 'Ezidi world',
    contact_email: 'contact@ezidi-world.org',
    poster_url: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&h=1000&fit=crop',
    status: 'published',
    visibility: 'public',
    event_verification_status: 'organization_verified',
    is_featured: false,
    is_demo: false,
    created_at: '2026-08-10T15:15:00Z',
    updated_at: '2026-08-10T15:15:00Z',
  },
  {
    id: 'event-1',
    slug: 'berlin-international-solidarity-rally-2026',
    title: 'International Solidarity Rally for Yazidi Justice & Genocide Recognition',
    title_ar: 'وقفة تضامنية دولية لتحقيق العدالة للإيزيديين والاعتراف بالإبادة الجماعية',
    title_de: 'Internationale Solidaritätskundgebung für Jesidische Gerechtigkeit',
    title_fr: 'Rassemblement international de solidarité pour la justice yézidie',
    description: 'وقفة تضامنية جماهيرية أمام بوابة براندنبورغ التاريخية في برلين للمطالبة بالعدالة الدولية ومحاسبة مجرمي الإبادة.',
    description_ar: 'وقفة تضامنية جماهيرية أمام بوابة براندنبورغ التاريخية في برلين للمطالبة بالعدالة الدولية ومحاسبة مجرمي الإبادة.',
    category_id: 'cat-solidarity',
    date: '2026-08-03',
    start_time: '16:00',
    end_time: '19:30',
    timezone: 'Europe/Berlin',
    country_id: 'c-de',
    city_id: 'city-berlin',
    full_address: 'Pariser Platz, 10117 Berlin, Germany',
    postal_code: '10117',
    street: 'Pariser Platz',
    house_number: '1',
    latitude: 52.5163,
    longitude: 13.3777,
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=52.5163,13.3777',
    organization_id: 'org-yazidi-solidarity',
    organizer_name: 'Yazidi Global Solidarity Initiative',
    poster_url: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=800&h=1000&fit=crop',
    status: 'published',
    visibility: 'public',
    event_verification_status: 'organization_verified',
    is_featured: true,
    is_demo: false,
    source_url: 'https://yazidi-solidarity.org/berlin-rally-2026',
    contact_email: 'events@yazidi-solidarity.org',
    created_at: '2026-06-01T00:00:00Z',
    updated_at: '2026-06-01T00:00:00Z',
  },
  {
    id: 'event-2',
    slug: 'lalish-annual-heritage-peace-conference-2026',
    title: 'Lalish Peace & Cultural Heritage Forum 2026',
    title_ar: 'منتدى لالش للسلام والتراث الثقافي 2026',
    title_de: 'Lalisch Friedens- und Kulturerbeforum 2026',
    title_fr: 'Forum de la paix et du patrimoine de Lalish 2026',
    description: 'مؤتمر دولي يجمع رجال الدين والباحثين والشباب لمناقشة صيانة معبد لالش وإعادة إعمار سنجار.',
    description_ar: 'مؤتمر دولي يجمع رجال الدين والباحثين والشباب لمناقشة صيانة معبد لالش وإعادة إعمار سنجار.',
    category_id: 'cat-conf',
    date: '2026-08-15',
    start_time: '10:00',
    end_time: '18:00',
    timezone: 'Asia/Baghdad',
    country_id: 'c-iq',
    city_id: 'city-lalish',
    full_address: 'Lalish Temple Complex, Shekhan District, Nineveh Plains, Iraq',
    latitude: 36.7725,
    longitude: 43.3039,
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=36.7725,43.3039',
    organization_id: 'org-lalish-center',
    organizer_name: 'Lalish Cultural & Heritage Center',
    poster_url: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&h=1000&fit=crop',
    status: 'published',
    visibility: 'public',
    event_verification_status: 'admin_verified',
    is_featured: true,
    is_demo: false,
    source_url: 'https://lalish-center.org/conference-2026',
    contact_email: 'contact@lalish-center.org',
    created_at: '2026-06-10T00:00:00Z',
    updated_at: '2026-06-15T00:00:00Z',
  },
  {
    id: 'event-3',
    slug: 'paris-candlelight-vigil-for-sinjar-survivors',
    title: 'Paris Vigil of Light: In Memory of Sinjar Victims',
    title_ar: 'وقفة شموع في باريس: وفاءً لضحايا وناجيات سنجار',
    title_de: 'Pariser Lichter-Mahnwache für die Überlebenden von Sindschar',
    title_fr: 'Veillée aux bougies à Paris : En mémoire des victimes de Sinjar',
    description: 'وقفة إضاءة شموع وعزف ألحان تراثية وقراءة شهادات الناجيات في ساحة الجمهورية بوسط باريس.',
    description_ar: 'وقفة إضاءة شموع وعزف ألحان تراثية وقراءة شهادات الناجيات في ساحة الجمهورية بوسط باريس.',
    category_id: 'cat-vigil',
    date: '2026-08-03',
    start_time: '19:30',
    end_time: '22:00',
    timezone: 'Europe/Paris',
    country_id: 'c-fr',
    city_id: 'city-paris',
    full_address: 'Place de la République, 75011 Paris, France',
    latitude: 48.8675,
    longitude: 2.3638,
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=48.8675,2.3638',
    organization_id: 'org-youth-peace',
    organizer_name: 'Youth for Yazidi Peace & Justice',
    poster_url: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&h=1000&fit=crop',
    status: 'published',
    visibility: 'public',
    event_verification_status: 'admin_verified',
    is_featured: false,
    is_demo: false,
    source_url: 'https://youth-yazidi.fr/paris-vigil',
    contact_email: 'contact@youth-yazidi.fr',
    created_at: '2026-06-20T00:00:00Z',
    updated_at: '2026-06-20T00:00:00Z',
  },
  {
    id: 'event-4',
    slug: 'lincoln-nebraska-yazidi-culture-and-food-fair',
    title: 'North American Yazidi Heritage & Cultural Exhibition',
    title_ar: 'معرض التراث والثقافة الإيزيدية في أمريكا الشمالية',
    title_de: 'Nordamerikanische Jesidische Kultur- und Kunstausstellung',
    title_fr: 'Exposition du patrimoine et de la culture yézidie d’Amérique du Nord',
    description: 'معرض تراثي وثقافي يضم فنوناً وأكلات تقليدية ومعارض صور وثائقية عن تاريخ وحياة المجتمع الإيزيدي.',
    description_ar: 'معرض تراثي وثقافي يضم فنوناً وأكلات تقليدية ومعارض صور وثائقية عن تاريخ وحياة المجتمع الإيزيدي.',
    category_id: 'cat-culture',
    date: '2026-09-12',
    start_time: '11:00',
    end_time: '17:00',
    timezone: 'America/Chicago',
    country_id: 'c-us',
    city_id: 'city-lincoln',
    full_address: '1500 R St, Lincoln, NE 68588, United States',
    latitude: 40.8176,
    longitude: -96.7005,
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=40.8176,-96.7005',
    organizer_name: 'Yazidi Community Association of Nebraska',
    poster_url: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800&h=1000&fit=crop',
    status: 'published',
    visibility: 'public',
    event_verification_status: 'admin_verified',
    is_featured: false,
    is_demo: false,
    source_url: 'https://nebraska-yazidi.org',
    created_at: '2026-06-22T00:00:00Z',
    updated_at: '2026-06-22T00:00:00Z',
  },
  {
    id: 'event-5',
    slug: 'sydney-human-rights-memorial-march',
    title: 'Sydney Solidarity March for Global Genocide Prevention & Justice',
    title_ar: 'مسيرة تضامنية في سيدني للعدالة ومنع الإبادة الجماعية',
    title_de: 'Sydney Solidaritätsmarsch zur Verhinderung von Völkermord',
    title_fr: 'Marche de solidarité à Sydney pour la prévention des génocides',
    description: 'مسيرة سلمية في سيدني لمساندة الشعب الإيزيدي والمطالبة بدعم برامج إعادة تأهيل الناجين.',
    description_ar: 'مسيرة سلمية في سيدني لمساندة الشعب الإيزيدي والمطالبة بدعم برامج إعادة تأهيل الناجين.',
    category_id: 'cat-rights',
    date: '2026-08-08',
    start_time: '14:00',
    end_time: '17:00',
    timezone: 'Australia/Sydney',
    country_id: 'c-au',
    city_id: 'city-sydney',
    full_address: 'Elizabeth St, Hyde Park, Sydney NSW 2000, Australia',
    latitude: -33.8732,
    longitude: 151.2106,
    google_maps_url: 'https://www.google.com/maps/search/?api=1&query=-33.8732,151.2106',
    organizer_name: 'Australian Yazidi Community Council',
    poster_url: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&h=1000&fit=crop',
    status: 'published',
    visibility: 'public',
    event_verification_status: 'admin_verified',
    is_featured: false,
    is_demo: false,
    created_at: '2026-06-25T00:00:00Z',
    updated_at: '2026-06-25T00:00:00Z',
  },
];

export const INITIAL_PENDING_CHANGES: EventPendingChange[] = [];
export const INITIAL_REPORTS: EventReport[] = [];
export const INITIAL_AUDIT_LOGS: AuditLog[] = [];
export const INITIAL_NOTIFICATIONS: NotificationItem[] = [];
